server:
  port: 9001
spring:
  application:
    name: ServiceA

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tx-manager?characterEncoding=UTF-8
    username: root
    password: 111111

    #type: com.alibaba.druid.pool.DruidDataSource
#  jpa:
#    generate-ddl: true
#    show-sql: true

#dubbo:
#  application:
#    name: dubbbo-ServiceA
#  server: true
#  registry:
#    address: 127.0.0.1:2181
#    protocol: zookeeper
#    protocol:
#      name: dubbo
#      port: 20880




dubbo:
  scan:
    basePackages: com.mt.serviceA.service.impl
#
#  # Dubbo Config properties
#  ## ApplicationConfig Bean
#  dubbo.application.id=DubboServiceBApplication
#  dubbo.application.name=DubboServiceBApplication
#
#  ## ProtocolConfig Bean
#  dubbo.protocol.id=dubbo
  protocol:
    id: dubbo
    name: dubbo
    port: 28880
  registry:
    id: my-registry
    address: 127.0.0.1:2181
    protocol: zookeeper
  application:
    qos-enable: false
    id: ServiceA
    name: ServiceA

#  dubbo.protocol.name=dubbo
#  dubbo.protocol.port=12345
#
#  ## RegistryConfig Bean
#  dubbo.registry.id=my-registry
#  dubbo.registry.address=127.0.0.1:2181
#  dubbo.registry.protocol=zookeeper
#  dubbo.application.qos.enable=false

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070

#mybatis-plus:
#  global-config:
#    db-config:
#      # 全局主键生成策略：自行输入
#      id-type: input
#  # mapper.xml文件扫描路径
#  mapper-locations: classpath*:mapper/*.xml
#logging:
#  level:
#    root: debug
