server:
  port: 8001

eureka:
  instance:
    #hostname: note-1
    prefer-ip-address: true
  client:
    registerWithEureka: false  #注册中心为单节点时，设置为false
    fetch-registry: false #注册中心为单节点时，设置为false
#    serviceUrl:
#      defaultZone: http://localhost:8079/eureka/,http://localhost:8078/eureka/
spring:
  application:
    name: note-1
  #profiles: note-1
